let movies = [
    "PULP FICTION",
    "FIGHT CLUB",
    "FOREST GUMP",
    "AŞK TESADÜFLERİ SEVER",
    "MUCİZE",
    "LEON",
    "A QUITE PLACE",
    "GOTFATHER",
    "DONIE DARKO",
    "SIXTH SENSE",
    "LA LA LAND",
    "TITANIC",
    "BEFORE THE SUNRISE",
    "PREDESTINATION",
    "TWELFE ANGRY MAN",
    "MEMENTO",
    "BABAM VE OĞLUM",
    "THE OTHERS",
    "HANGOVER",
    "THE CONJURING",
    "FAST AND FURIOUS",
    "AVENGERS",
    "BRAVEHEART",
    "SEASON OF THE WITCH",
    "AVATAR",
    "TRANSPORTER",
    "INCEPTION",
    "HUNGER GAMES",
    "IMMORTALS",
    "JURASSIC PARK"
];


